[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
      \ 'colorscheme': 'powerline',
      \ 'component': {
      \   'readonly': '%{&readonly?"✗":""}',
      \ },
      \ 'separator': { 'left': "", 'right': "" },
      \ 'subseparator': { 'left': ">", 'right': "<" },
      \ }
'''

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
  let g:EditorConfig_exec_path = '/usr/local/bin/editorconfig'
  let g:Editorconfig_core_mode = 'python_external'
'''
