[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug','jade']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

