set nocompatible
set backspace=indent,eol,start

set nobackup
set viminfo=!,'50,<1000,s100,\"50 "
set history=100

"
" dein.vim
"
let s:dein_dir = expand('~/.cache/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
let s:dein_toml_path = '~/.vim/rc/dein.toml'
let s:dein_lazy_toml_path = '~/.vim/rc/dein_lazy.toml'

if &runtimepath !~ '/dein.vim'
  if !isdirectory(s:dein_repo_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

if dein#load_state(s:dein_dir)
    call dein#begin(s:dein_dir)
    call dein#load_toml(s:dein_toml_path, {'lazy': 0})
    call dein#load_toml(s:dein_lazy_toml_path, {'lazy': 1})

    call dein#end()
    call dein#save_state()
endif

if has('vim_starting') && dein#check_install()
    call dein#install()
endif

" 補完時に無視されるファイル名のsuffix
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc

"
" 画面表示の設定
"
syntax on          " シンタックスを表示する
set number         " 行番号を表示する
set cursorline     " カーソル行の背景色を変える
set laststatus=2   " ステータス行を常に表示
set cmdheight=2    " メッセージ表示欄を2行確保
set modelines=1
" 括弧の対応表示時間
set showmatch matchtime=0
set helpheight=999 " ヘルプを画面いっぱいに開く
set list           " 不可視文字を表示
" 不可視文字の表示記号指定
set listchars=tab:\|\ ,trail:-,extends:❯,precedes:❮
" カラースキーマ設定
if has('nvim')
"    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif
set t_Co=256
colorscheme molokai

" マウスを有効にする
if has('mouse')
	set mouse=a
endif
" プラグインを使用可能にする
filetype on
filetype plugin on
filetype indent on
" 自動的にインデントする
set autoindent
set smartindent
set cindent
" タイトルを表示
set title
" 右下に表示される行・列の番号を表示する
set ruler
" タブ幅設定
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
" カーソルライン表示
set cursorline
" クリップボード共有
"set clipboard=unnamed,autoselect
" タブを空白文字に変換
set expandtab

"検索文字列が小文字の場合は大文字小文字を区別なく検索する
set ignorecase
"検索文字列に大文字が含まれている場合は区別して検索する
set smartcase
"検索時に最後まで行ったら最初に戻る
set wrapscan
"検索文字列入力時に順次対象文字列にヒットさせる
set incsearch
"入力中のコマンドをステータスに表示する
set showcmd
"括弧入力時の対応する括弧を表示
set showmatch
"検索結果文字列のハイライトを有効にする
set hlsearch

" コマンドライン補完するときに強化されたものを使う(参照 :help wildmenu)
set wildmenu
" コマンドライン補間をシェルっぽく
set wildmode=list:longest
" バッファが編集中でもその他のファイルを開けるように
set hidden
" 外部のエディタで編集中のファイルが変更されたら自動で読み直す
set autoread

" 文字コードの自動認識
" from ずんWiki http://www.kawaz.jp/pukiwiki/?vim#content_1_7
set encoding=utf-8
set fileencoding=utf-8
if &encoding !=# 'utf-8' " utf-8をデフォルトに
  set encoding=japan
  set fileencoding=japan
endif
if has('iconv')
  let s:enc_euc = 'euc-jp'
  let s:enc_jis = 'iso-2022-jp'
  " iconvがeucJP-msに対応しているかをチェック
  if iconv("¥x87¥x64¥x87¥x6a", 'cp932', 'eucjp-ms') ==# "¥xad¥xc5¥xad¥xcb"
    let s:enc_euc = 'eucjp-ms'
    let s:enc_jis = 'iso-2022-jp-3'
  " iconvがJISX0213に対応しているかをチェック
  elseif iconv("¥x87¥x64¥x87¥x6a", 'cp932', 'euc-jisx0213') ==# "¥xad¥xc5¥xad¥xcb"
    let s:enc_euc = 'euc-jisx0213'
    let s:enc_jis = 'iso-2022-jp-3'
  endif
  " fileencodingsを構築
  if &encoding ==# 'utf-8'
    let s:fileencodings_default = &fileencodings
    let &fileencodings = s:enc_jis .','. s:enc_euc .',cp932'
    let &fileencodings = &fileencodings .','. s:fileencodings_default
    unlet s:fileencodings_default
  else
    let &fileencodings = &fileencodings .','. s:enc_jis
    set fileencodings+=utf-8,ucs-2le,ucs-2
    if &encoding =~# '^¥(euc-jp¥|euc-jisx0213¥|eucjp-ms¥)$'
      set fileencodings+=cp932
      set fileencodings-=euc-jp
      set fileencodings-=euc-jisx0213
      set fileencodings-=eucjp-ms
      let &encoding = s:enc_euc
      let &fileencoding = s:enc_euc
    else
      let &fileencodings = &fileencodings .','. s:enc_euc
    endif
  endif
  let &fileencodings = 'utf-8' . ',' . &fileencodings " XXX: adhocな対応
  " 定数を処分
  unlet s:enc_euc
  unlet s:enc_jis
endif

" 日本語を含まない場合は fileencoding に encoding を使うようにする
if has('autocmd')
  function! AU_ReCheck_FENC()
    if &fileencoding =~# 'iso-2022-jp' && search("[^¥x01-¥x7e]", 'n') == 0
      let &fileencoding=&encoding
    endif
  endfunction
  autocmd BufReadPost * call AU_ReCheck_FENC()
endif


" 改行コードの自動認識
set fileformats=unix,dos,mac

" □とか○の文字があってもカーソル位置がずれないようにする
set ambiwidth=double

" 辞書ファイルからの単語補間
set complete+=k

nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

" ブラケット入力補助
function! CloseBrackets(rbracket)
    let char = getline('.')[col('.') - 1]
    if     char != "\"" && a:rbracket == "\""
        return "\"\"\<Left>"
    elseif char != "\'" && a:rbracket == "\'"
        return "\'\'\<Left>"
    elseif char == a:rbracket
        return "\<Right>"
    else
        return a:rbracket
    endif
endfunction

function! DeleteBrackets()
    let pos = col('.') - 1
    let line = getline('.')
    let lbrackets = ['(', '{', '[', "\'", "\""]
    let rbrackets = [')', '}', ']', "\'", "\""]
    let i = 0
    let output = ''

    if pos == strlen(line)
        return "\b"
    endif
    for c in lbrackets
        if line[pos-1] == c && line[pos] == rbrackets[i]
            let output = "\<Right>\b"
            break
        endif
        let i += 1
    endfor
    return output."\b"
endfunction

inoremap ( ()<Left>
inoremap { {}<Left>
inoremap [ []<Left>
inoremap <silent> ) <C-R>=CloseBrackets(")")<CR>
inoremap <silent> } <C-R>=CloseBrackets("}")<CR>
inoremap <silent> ] <C-R>=CloseBrackets("]")<CR>
inoremap <silent> " <C-R>=CloseBrackets("\"")<CR>
inoremap <silent> ' <C-R>=CloseBrackets("\'")<CR>
inoremap <silent> <BS> <C-R>=DeleteBrackets()<CR>

" Shift+Enter(Ctrl+])で新しい行
inoremap <S-CR> <Esc>o
inoremap <C-]> <Esc>o

