---
- name: Install zsh
  homebrew:
    name: zsh

- name: Add installed zsh in shells
  lineinfile:
    path: /etc/shells
    line: '/usr/local/bin/zsh'
  become: yes

- name: Use installed zsh
  shell: chsh -s /usr/local/bin/zsh
