---
- name: Install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: Add cargo path
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR CARGO"
    content: |
      source $HOME/.cargo/env
