---
- name: Install pyenv
  homebrew:
    name: pyenv

- name: Add pyenv path
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR PYENV"
    content: |
      export PYENV_ROOT=$HOME/.pyenv
      export PATH=$PYENV_ROOT/bin:$PATH
      if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
      fi

- name: Get latest Python2 version
  shell: pyenv install -l | grep -e '2.[0-9]\+.[0-9]\+$' | grep -v - | tail -1
  register: python2_version

- name: Get latest Python3 version
  shell: pyenv install -l | grep -e '3.[0-9]\+.[0-9]\+$' | grep -v - | tail -1
  register: python3_version

- name: Install Python2
  shell: "pyenv install {{ python2_version.stdout }}"
  ignore_errors: yes

- name: Install Python3
  shell: "pyenv install {{ python3_version.stdout }}"
  ignore_errors: yes

- name: Use installed python
  shell: "pyenv global {{ python3_version.stdout }} {{ python2_version.stdout }}"

- name: Install python packages
  pip:
    executable: pip3
    name:
      #- chainer
      - Cython
      - Flask
      #- fonttools
      - jupyter
      - jupyterlab
      - numpy
      - pandas
      #- pycairo
      - requests
      - setuptools
      - scikit-learn
      - scipy
      - six
      - tables
      #- tensorflow
      #- tensorflow-tensorboard
      - wheel
